[tool.ruff]
target-version = "py310"
line-length = 100
indent-width = 4

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP", "B"]
ignore = [
	"W191",
	"D206",
	"UP015",
	"E203",
	"E266"
]

[tool.ruff.format]
indent-style = "tab"
line-ending = "auto"
quote-style = "preserve"
skip-magic-trailing-comma = false

[tool.pydocstyle]
ignore = [	
	"D107",
	"D100",
	"D101",
	"D102",
	"D401",
	"D400",
	"D205",
	"D212",
	"D413",
	"D406",
	"D203",
	"D415",
	"D411",
	"D407",
]
